import { Link } from "react-router-dom";
import { Flame, ArrowLeft, Mail, MessageSquare, ExternalLink } from "lucide-react";
import { motion } from "motion/react";
import { SOCIALS, SUPPORT_EMAIL } from "../lib/mockups";

export function LegalShell({ title, kicker, children }) {
  return (
    <div className="min-h-screen relative overflow-hidden">
      <div className="absolute inset-0 grid-bg opacity-30 pointer-events-none" />
      <div className="orb orb-purple w-[500px] h-[500px] -top-40 -right-32 opacity-20" />
      <div className="orb orb-cyan w-[400px] h-[400px] -bottom-40 -left-32 opacity-15" />

      {/* Top bar */}
      <header className="sticky top-0 z-30 bg-[#05050a]/85 backdrop-blur-xl border-b border-purple-500/15">
        <div className="max-w-5xl mx-auto px-5 sm:px-8 h-16 flex items-center justify-between">
          <Link to="/" className="flex items-center gap-2.5">
            <span className="h-9 w-9 rounded-xl bg-gradient-to-br from-purple-500 to-fuchsia-700 grid place-items-center glow-purple">
              <Flame className="h-5 w-5 text-white" strokeWidth={2.5} />
            </span>
            <div className="leading-tight">
              <div className="font-display font-extrabold tracking-tight">REVENGE ARC</div>
              <div className="text-[10px] tracking-[0.4em] text-cyan-300/80">{kicker}</div>
            </div>
          </Link>
          <Link to="/" className="btn-ghost !py-2 !px-4 !text-sm">
            <ArrowLeft className="h-4 w-4" /> Back home
          </Link>
        </div>
      </header>

      <main className="relative max-w-3xl mx-auto px-5 sm:px-8 py-16">
        <motion.div
          initial={{ opacity: 0, y: 14 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.6 }}
        >
          <div className="text-[11px] tracking-[0.35em] text-purple-300 font-bold mb-3">{kicker}</div>
          <h1 className="font-display font-extrabold text-4xl sm:text-5xl lg:text-6xl tracking-tight">{title}</h1>
          <p className="text-white/45 text-sm mt-3">Last updated: February 2026</p>
        </motion.div>

        <motion.article
          initial={{ opacity: 0, y: 14 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.7, delay: 0.05 }}
          className="mt-10 glass rounded-3xl p-6 sm:p-8 prose-revenge"
        >
          {children}
        </motion.article>

        <div className="mt-10 text-center text-sm text-white/45">
          Questions? Reach us at <a href={`mailto:${SUPPORT_EMAIL}`} className="text-purple-300 hover:text-purple-200">{SUPPORT_EMAIL}</a>
        </div>
      </main>
    </div>
  );
}

const H = ({ children }) => <h2 className="font-display font-extrabold text-2xl text-white mt-7 mb-3 first:mt-0">{children}</h2>;
const P = ({ children }) => <p className="text-white/75 leading-relaxed mb-3 text-[15px]">{children}</p>;
const Ul = ({ items }) => (
  <ul className="space-y-2 mb-3">
    {items.map((i) => (
      <li key={typeof i === "string" ? i : JSON.stringify(i)} className="text-white/75 text-[15px] flex items-start gap-2.5">
        <span className="mt-2 h-1.5 w-1.5 rounded-full bg-purple-400 flex-shrink-0" />
        <span>{i}</span>
      </li>
    ))}
  </ul>
);

export function TermsPage() {
  return (
    <LegalShell title="Terms of Service" kicker="LEGAL">
      <P>By accessing or using Revenge Arc — including our website, applications, and services — you agree to these Terms of Service. If you do not agree, please do not use the service.</P>

      <H>1. AI Disclaimer</H>
      <P>Revenge Arc uses AI-powered tools (including Gym Buddie AI, AI Food Scan, AI Form Lab, and AI weekly reports). AI outputs are generated by automated models and may contain errors, inaccuracies, or hallucinations. AI guidance is provided for informational and motivational purposes only and is not a substitute for professional advice.</P>

      <H>2. Fitness & Health Disclaimer</H>
      <P>Revenge Arc is not a medical device, diagnostic tool, or substitute for advice from a qualified healthcare professional, dietitian, or licensed trainer. Consult a doctor before beginning any exercise or nutrition program, especially if you have pre-existing conditions, injuries, or are pregnant.</P>
      <Ul items={[
        "Workouts, macros, and AI suggestions are provided as-is.",
        "Listen to your body; stop if you feel pain or discomfort.",
        "Results vary and are not guaranteed.",
      ]} />

      <H>3. Liability Limitations</H>
      <P>To the maximum extent permitted by law, Revenge Arc and its team are not liable for any direct, indirect, incidental, consequential, or punitive damages arising from your use of the service, including (but not limited to) physical injury, lost data, or financial loss. You assume full responsibility for your training, nutrition, and recovery decisions.</P>

      <H>4. Subscription Terms</H>
      <P>Premium subscriptions are billed monthly or yearly via the in-app payment processor at the time of launch. Subscriptions auto-renew unless canceled before the next billing cycle. Refunds are governed by our Refund Policy.</P>

      <H>5. Account Responsibilities</H>
      <Ul items={[
        "You're responsible for keeping your login credentials secure.",
        "You must be at least 13 years old (or the legal minimum in your country) to use Revenge Arc.",
        "You agree not to share, resell, or scrape the platform.",
        "We may suspend or terminate accounts that violate these Terms.",
      ]} />

      <H>6. Acceptable Use</H>
      <P>You agree not to use the service to harass, harm, or harvest data from other users, post unlawful content, attempt to reverse-engineer the platform, or interfere with normal operation.</P>

      <H>7. Changes</H>
      <P>We may update these Terms periodically. Material changes will be communicated via email or in-app notice. Continued use after updates means you accept the revised Terms.</P>

      <H>8. Contact</H>
      <P>Questions? Email <a className="text-purple-300 hover:text-purple-200" href={`mailto:${SUPPORT_EMAIL}`}>{SUPPORT_EMAIL}</a>.</P>
    </LegalShell>
  );
}

export function PrivacyPage() {
  return (
    <LegalShell title="Privacy Policy" kicker="LEGAL">
      <P>This Privacy Policy explains what data Revenge Arc collects, how we use it, and the rights you have over it.</P>

      <H>1. Data We Collect</H>
      <Ul items={[
        "Account data (name, email, device type, profile info, password hashes)",
        "Waitlist submissions and creator applications",
        "Workout, nutrition, body, and progress tracking entries",
        "Uploaded images (progress photos, food photos for AI Food Scan)",
        "AI conversation history with Gym Buddie AI",
        "Subscription and billing metadata (payment processor handles raw card data)",
        "Support communications (emails, chat messages)",
        "Anonymized analytics on app usage and feature engagement",
      ]} />

      <H>2. How We Store Your Data</H>
      <P>User data is stored securely in our cloud database. Uploaded media (images, progress photos, food photos) is stored in Firebase Storage with restricted, signed access. AI analysis runs against encrypted requests; AI providers do not retain training data on your private content.</P>

      <H>3. How We Use Your Data</H>
      <Ul items={[
        "Deliver the Revenge Arc service (tracking, AI coaching, analytics)",
        "Generate personalized AI insights and weekly reports",
        "Process creator applications and waitlist signups",
        "Send transactional and product update emails",
        "Improve product features via aggregated, anonymized analytics",
        "Detect and prevent fraud, abuse, and account compromise",
      ]} />

      <H>4. Sharing</H>
      <P>We do not sell your personal data. We share data only with vetted infrastructure providers (cloud hosting, AI inference, email delivery, analytics) under strict confidentiality and processing agreements. Approved creators may receive aggregated, anonymized engagement metrics.</P>

      <H>5. Security</H>
      <P>We use TLS encryption for data in transit, encrypted-at-rest storage, hashed passwords (bcrypt), scoped API tokens, and access logging. Despite our efforts, no system is 100% secure — we encourage strong, unique passwords and 2FA where available.</P>

      <H>6. Your Rights</H>
      <Ul items={[
        "Access and download your data",
        "Request correction or deletion",
        "Export your tracking history",
        "Withdraw consent for marketing emails at any time",
      ]} />
      <P>To exercise any right, email <a className="text-purple-300 hover:text-purple-200" href={`mailto:${SUPPORT_EMAIL}`}>{SUPPORT_EMAIL}</a>.</P>

      <H>7. Children</H>
      <P>Revenge Arc is not directed to children under 13. We do not knowingly collect data from anyone under 13.</P>

      <H>8. Updates</H>
      <P>This policy may be updated as the product evolves. The "Last updated" date above will reflect changes.</P>
    </LegalShell>
  );
}

export function RefundPage() {
  return (
    <LegalShell title="Refund Policy" kicker="LEGAL">
      <H>Subscription Refunds</H>
      <P>Premium subscriptions are billed via the in-app payment processor (Apple App Store or Google Play). Refund requests must be submitted through the platform that processed the original transaction:</P>
      <Ul items={[
        "Apple App Store: Settings → [Your Name] → Subscriptions → Report a Problem",
        "Google Play: Play Store → Account → Subscriptions → Cancel/Refund",
      ]} />

      <H>Free Trials</H>
      <P>If a free trial is offered, you can cancel at any time before it ends to avoid being charged.</P>

      <H>Disputes</H>
      <P>If you believe a charge was made in error or you experienced a service issue, contact us at <a className="text-purple-300 hover:text-purple-200" href={`mailto:${SUPPORT_EMAIL}`}>{SUPPORT_EMAIL}</a> within 14 days of the charge. We'll review your case and work with you to resolve it.</P>

      <H>Cancellations</H>
      <P>You may cancel your Premium subscription at any time. Access to Premium features remains until the end of the current billing period; auto-renewal is stopped immediately.</P>

      <H>No Refunds For</H>
      <Ul items={[
        "Partially used billing periods (after cancellation)",
        "Account suspensions for Terms violations",
        "Promotional or discounted plans purchased outside official platforms",
      ]} />
    </LegalShell>
  );
}

export function ContactPage() {
  return (
    <LegalShell title="Contact" kicker="GET IN TOUCH">
      <P>We read every email. For the fastest response:</P>

      <H>General & Support</H>
      <a href={`mailto:${SUPPORT_EMAIL}`} className="inline-flex items-center gap-2 px-4 py-3 rounded-xl border border-purple-500/40 bg-purple-500/10 text-purple-200 font-bold hover:bg-purple-500/20 transition mb-6">
        <Mail className="h-4 w-4" /> {SUPPORT_EMAIL}
      </a>

      <H>Community</H>
      <div className="flex flex-wrap gap-3">
        <a href={SOCIALS.discord} target="_blank" rel="noreferrer" className="inline-flex items-center gap-2 px-4 py-3 rounded-xl border border-indigo-500/40 bg-indigo-500/10 text-indigo-200 font-bold hover:bg-indigo-500/20 transition">
          <MessageSquare className="h-4 w-4" /> Discord <ExternalLink className="h-3.5 w-3.5" />
        </a>
        <a href={SOCIALS.instagram} target="_blank" rel="noreferrer" className="inline-flex items-center gap-2 px-4 py-3 rounded-xl border border-pink-500/40 bg-pink-500/10 text-pink-200 font-bold hover:bg-pink-500/20 transition">
          Instagram <ExternalLink className="h-3.5 w-3.5" />
        </a>
        <a href={SOCIALS.tiktok} target="_blank" rel="noreferrer" className="inline-flex items-center gap-2 px-4 py-3 rounded-xl border border-cyan-500/40 bg-cyan-500/10 text-cyan-200 font-bold hover:bg-cyan-500/20 transition">
          TikTok <ExternalLink className="h-3.5 w-3.5" />
        </a>
      </div>

      <H>Creator Partnerships</H>
      <P>Submit your application via the <Link to="/creator" className="text-purple-300 hover:text-purple-200">Creator Program page</Link>. Every application is reviewed manually.</P>

      <H>Press</H>
      <P>Press inquiries: email <a className="text-purple-300 hover:text-purple-200" href={`mailto:${SUPPORT_EMAIL}`}>{SUPPORT_EMAIL}</a> with subject line "Press —".</P>
    </LegalShell>
  );
}

export function SupportPage() {
  return (
    <LegalShell title="Support" kicker="HELP CENTER">
      <P>Need help? Here's how to reach us — and what to expect.</P>

      <H>Email Support</H>
      <a href={`mailto:${SUPPORT_EMAIL}`} className="inline-flex items-center gap-2 px-4 py-3 rounded-xl border border-purple-500/40 bg-purple-500/10 text-purple-200 font-bold hover:bg-purple-500/20 transition mb-6">
        <Mail className="h-4 w-4" /> {SUPPORT_EMAIL}
      </a>
      <P>Response time: typically within 24–48 hours on business days.</P>

      <H>Common Questions</H>
      <Ul items={[
        "When will the app launch? — Private beta now; early access goes out to waitlist warriors first.",
        "How do I cancel my subscription? — See the Refund Policy for App Store / Play Store cancellation steps.",
        "I forgot my password. — Use the in-app password reset, or email support if you can't access your email.",
        "AI gave me wrong info. — AI outputs are guidance, not medical/legal advice. See our AI Disclaimer in the Terms.",
        "I want to delete my account. — Email support and we'll wipe your data within 7 days.",
      ]} />

      <H>Community Support</H>
      <P>Join our <a href={SOCIALS.discord} target="_blank" rel="noreferrer" className="text-purple-300 hover:text-purple-200">Discord</a> for real-time community help and announcements.</P>

      <H>Bug Reports</H>
      <P>Found a bug? Email <a className="text-purple-300 hover:text-purple-200" href={`mailto:${SUPPORT_EMAIL}`}>{SUPPORT_EMAIL}</a> with subject "Bug —" and include device, OS version, and steps to reproduce.</P>
    </LegalShell>
  );
}
